### ISSUE TITLE
[Bia10-CombatClass-Bugs] Todo list

### ISSUE THREAD

**Issue by Bia10** [Jnnshschl/AmeisenBotX#110]
- [ ] Ranged classes  wont move closer if enemy is not in LOS

- [ ] Ranged classes will move closer upon first cast

- [ ] Melee classes interacting with target end up with too quick animations being played, something wrong with                     `Bot.Wow.InteractWithUnit(target.BaseAddress);`

- [ ] Warrior335a.VictoryRush requires tracking of time elapsed since last kill for proper timing
